version: '3.7'

services:
  nginx:
    build: ./nginx
    image: myapp-nginx:latest
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    secrets:
      - source: cssnr_basic_http_auth
        target: /etc/nginx/auth.users
    networks:
      - redbot-internal
    ports:
      - "80:80"
    depends_on:
      - app
      - redis-commander
#      - uptime-kuma
#      - pgadmin

  app:
    build: ./app
    image: myapp-app:latest
    env_file: settings.env
    command: "gunicorn myapp.wsgi:application -b 0.0.0.0:9000 -w 2"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9000/app-health-check/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    networks:
      - redbot-internal

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1
      - URL_PREFIX=/redis
      - TRUST_PROXY=true
    deploy:
      replicas: 1
    networks:
      - redbot-internal

#  uptime-kuma:
#    image: louislam/uptime-kuma:1
#    deploy:
#      replicas: 1
#    volumes:
#      - uptime_data:/app/data
#    networks:
#      - redbot-internal
#    ports:
#      - "3001:3001"

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=shane@cssnr.com
#      - PGADMIN_DEFAULT_PASSWORD=torrent1
#      - PGADMIN_LISTEN_PORT=8082
#    deploy:
#      replicas: 1
#    volumes:
#      - redis_data:/data

secrets:
  cssnr_basic_http_auth:
    file: ~/basic_http_auth

volumes:
  data_dir:
  uptime_data:

networks:
  redbot-internal:
    name: "redbot-internal"
    external: true
